### PR TITLE
upgrade orchestrator-core to v4.14.1

### PR DESCRIPTION
**Pull request by hcyang**
This is a simple upgrade.

### CODE REVIEW

**Review by tsuwandy — APPROVED** [review]
@hcyang, installing bf cli rc version on npmjs will pull down orchestrator-core 4.14.1 because of the ~4.14.0 specification in orchestratorlib package.json.  

I suppose you only want this for testing locally?

**Comment by hcyang** [comment]
> @hcyang, installing bf cli rc version on npmjs will pull down orchestrator-core 4.14.1 because of the ~4.14.0 specification in orchestratorlib package.json.
> 
> I suppose you only want this for testing locally?

I suppose you were asking why I only try to check into 'main' not v4.14 rc. We can do that, too, but for the moment we have been helping one client using the nightly build.

**Comment by hcyang** [comment]
@munozemilio, this PR only do two things:
1) update package.json and upgrade orchestrator-core to v4.14.1.
2) remove and recreate a new copy of 'pnpm-lock.yaml'

Rebuild can only be successful after fixing one line in chatdown\convert.ts
from

    await new Promise(done => process.stdout.write(output, 'utf-8', () => done()))

to

    await new Promise((resolve, _) => process.stdout.write(output, 'utf-8', () => resolve("done")))

However, there are plenty of 'rush test' error in bf-lu and bf-lg-cli. Please take a look.

**Comment by tracyboehrer** [comment]
Closing.  Stale.  Was changed to latest patch version some time ago.

**Pull request closed without merging**
