### PR TITLE
Fix trailing tab after qna questions is not recognized issue

### LINKED ISSUE #1007: qnamaker:build cannot recognize trailing tab after questions
## Versions
4.10.1

## Describe the bug
qnamaker:build cannot recognize trailing tabs after questions and it will output errors like below:
line 6:13 token recognition error at: ' '
line 13:17 token recognition error at: '        '

## To Reproduce
1. use qnamaker:build to build a qna file whose questions have trailing tabs

## Expected behavior
No errors

## Additional context

[bug]

### PR DESCRIPTION
**Pull request by feich-ms**
fix #1007 to make qna parser recognize trailing tabs after questions

### CODE REVIEW

**Review by tsuwandy — APPROVED** [review]
Thanks @feich-ms

**Review by boydc2014 — APPROVED** [review]

**Comment by feich-ms** [comment]
@munozemilio hi, do you have any insights why the required CI validation is always pending?
image

**Review by boydc2014 — APPROVED** [review]

**Pull request merged**
