### PR TITLE
fix pattern issue reported by composer in cross train lib

### PR DESCRIPTION
**Pull request by feich-ms**
Fix issue reported in composer here https://github.com/microsoft/BotFramework-Composer/issues/2749. It was marked as P0 of R9 RC just recently(5.5). If we think this is release blocker for composer, we should make it in.
The main changes are removing all patterns with prebuilt entity as patternany entity in Interruption intent. For other patterns, we still keep them in Interruption intent.

### CODE REVIEW

**Comment by boydc2014** [comment]
Looks good to me on this one, @vishwacsena can you take this in next RC?

**Comment by munozemilio** [comment]
Hi Fei, can you please cherry-pick and do another PR against 4.9 branch? RC is there

**Comment by feich-ms** [comment]
@munozemilio I have cherry-picked the commit into this PR https://github.com/microsoft/botframework-cli/pull/759 targeting 4.9. Close this one since it's duplicated with #759

**Comment by munozemilio** [comment]
Hi @feich-ms , we need to PR's, one for master and one for R9

**Pull request closed without merging**
