### PR TITLE
Changes to support Luis schema v6.0.0

### LINKED ISSUE #453: LUISgen generates bad C# files from JSON app file
From attached JSON file, that was generated by preview.luis.ai - generated C# file has only sections

```
            // Simple entities
            public string[] amount;
            public string[] [object_Object];
            public string[] [object_Object];
            public string[] directionWithAddress;
            public string[] [object_Object];
            public string[] [object_Object];
            public string[] [object_Object];
            public string[] valueCurrency;
            public string[] [object_Object];
            public string[] [object_Object];
```
while for example entity `directionWithAddress` is not simple from JSON section

```
{
      "name": "directionWithAddress",
      "children": [
        {
          "name": "direction2",
          "children": [],
          "features": [
            {
              "featureName": "direction"
            }
          ]
        },
        {
          "name": "id",
          "children": [],
          "features": []
        },
        {
          "name": "network",
          "children": [],
          "features": []
        }
      ],
      "roles": [],
      "features": []
    },
```
[TransferFunds.zip](https://github.com/microsoft/botframework-cli/files/3999164/TransferFunds.zip)

### PR DESCRIPTION
**Pull request by axelsrz**
fixes #453

### CODE REVIEW

**Comment by chrimc62** [comment]
My only feedback is where are the tests?

**Comment by rurounijones** [comment]
Ahoi all. This has been sitting in limbo for nearly 3 weeks. Is there an ETA / priority for this?

**Comment by munozemilio** [comment]
Build is fix but I think some tests are missing

**Pull request merged**
